### ISSUE TITLE
[docs] either embed the fonts or convert text to paths

### ISSUE THREAD

**Issue by DanielRuf** [yowainwright/developer-ci-benefits#39]
## Requested Update
Currently the fonts used in the images are not installed on most clients so they look a bit weird.

## Why Is This Update Needed?
![github com_danielruf_developer-ci-benefits_blob_master_docs_04-ci-solves-problems md 1](https://user-images.githubusercontent.com/827205/43359700-0b92f9bc-92a7-11e8-8ae7-fea42fe9252e.png)

## Are There Examples Of This Requested Update Elsewhere?

> Read about references issues [here](https://help.github.com/articles/closing-issues-using-keywords/). Provide paragraph text responses to each header.

**Comment by yowainwright** [comment]
@DanielRuf Thanks for letting me know!

**Comment by yowainwright** [comment]
@DanielRuf the fonts should be embedded now.

**Comment by DanielRuf** [comment]
Seems to be sans-serif now but still looks mangled on mobile.

Did not yet check on desktop.

**Comment by DanielRuf** [comment]
I can still not see any embedded fonts here: view-source:https://jeffry.in/assets/developer-ci-benefits/04-ci-solves-problems.svg

**Comment by DanielRuf** [comment]
I guess there were some forgotten, eg view-source:https://jeffry.in/assets/developer-ci-benefits/04-ci-solves-problems.svg?1 ;-)
